# mtn-huts Overview over mountain huts in Switzerland.



= Initial Steps

NOTE: install 'poetry'

Go into your workdir:

  cd ~/.../mtn-huts

Create a virtual environment and install requirements:

  poetry install

Activate virtual enviroment:

  poetry shell

= Commands

In order to run your scripts you need to active the virtual enviroment for this project.
If not created yet follow the initial steps, if installed already you need todo the following
two steps:

  cd ~/.../mtn-huts
  poetry shell


== Local run

  ./wsgy.py
  

== Production

  gunicorn -w 4 -b localhost:8080 wsgi:application 


== Translation

=== Extract messages

  pybabel extract -F main/babel.cfg -k _l -o messages.pot .

=== Init Translation Files

NOTE: Only needed the frist time

  pybabel init -i messages.pot -d main/translations -l de
  pybabel init -i messages.pot -d main/translations -l fr
  pybabel init -i messages.pot -d main/translations -l it

=== Init or Update Translation Files

  pybabel update -i messages.pot -d main/translations


=== Compile Translations

  pybabel compile -d main/translations

